version: '3'

services:
  # Main frontend application service
  frontend:
    build:
      context: .
      dockerfile: docker/DockerfileDev
    container_name: inspiritaly-frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network
    command: npm run dev

  # Production build service (commented out by default)
  # Use this for testing production builds locally
  # frontend-prod:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: inspiritaly-frontend-prod
  #   ports:
  #     - '3001:3000'
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=3000
  #     - NODE_ENV=production
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
