version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/DockerfileDev
    container_name: inspiritaly-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
